### ISSUE TITLE
Correlated methods fail for ROHF references

### ISSUE THREAD

**Issue by jarrodmcc** [sunqm/pyscf#100]
It appears that there is an issue with running some correlated methods, specifically CISD and CCSD using an ROHF reference.  It does not flag "Not Implemented", but rather fails on any test I run with an error such as

```
Traceback (most recent call last):
  File "00-simple_cisd.py", line 18, in <module>
    mycc = ci.CISD(mf).run()
  File "/home/jmcclean/local/pyscf/lib/misc.py", line 299, in run
    self.kernel(*args)
  File "/home/jmcclean/local/pyscf/ci/cisd.py", line 454, in kernel
    return self.cisd(ci0, mo_coeff, eris)
  File "/home/jmcclean/local/pyscf/ci/cisd.py", line 460, in cisd
    tol=self.conv_tol, verbose=self.verbose)
  File "/home/jmcclean/local/pyscf/ci/cisd.py", line 32, in kernel
    diag = make_diagonal(mol, mo_energy, eris, nocc)
  File "/home/jmcclean/local/pyscf/ci/cisd.py", line 71, in make_diagonal
    eris_vvvv = ao2mo.restore(1, eris.vvvv, nvir)
  File "/home/jmcclean/local/pyscf/ao2mo/addons.py", line 124, in restore
    raise ValueError('eri.size = %d, norb = %d' % (eri.size, norb))
```
EDIT: Seems to work for FCI, but still not CISD or CCSD.

**Comment by gkc1000** [comment]
I think this is the same as #101, which has been closed. Qiming - if so, this can be closed.

**Comment by sunqm** [comment]
UCISD is not available.  I'll implement UCISD recently.
