### ISSUE TITLE
RCCSD error for atoms

### ISSUE THREAD

**Issue by aannabe** [sunqm/pyscf#101]
Hi, it looks like we have an RCCSD error for atoms. For instance, take a look at this one:
``` python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpv5z'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 0
mol.build()
hf = scf.ROHF(mol)
hf.irrep_nelec = {
'Ag' : (2,2),
'B3u': (1,0),
'B2u': (0,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.RCCSD(hf)
mycc.kernel()
```
Output:
```
converged SCF energy = -24.529109406518
Traceback (most recent call last):
  File "sae.py", line 26, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 191, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 210, in ccsd
    verbose=self.verbose)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 30, in kernel
    t1, t2 = cc.init_amps(eris)[1:]
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 179, in init_amps
    eijab = lib.direct_sum('ia,jb->ijab',eia,eia)
  File "/home/gani/codes/pyscf/pyscf/lib/numpy_helper.py", line 620, in direct_sum
    assert(len(symb) == op.ndim)
AssertionError
``` 
Thank you.

**Comment by gkc1000** [comment]
Hi, there is no restricted open-shell CC. Open shell systems need to be run
as UCCSD.

Probably we should flag this error, or have ccsd(...) automatically
dispatch to the right CC.

Garnet
