### ISSUE TITLE
UCCSD/CCSD frozen core issues on atoms

### ISSUE THREAD

**Issue by aannabe** [sunqm/pyscf#102]
Hi, frozen core seems to be not working. I have the following:
```python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpvtz'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 0
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (2,2),
'B3u': (1,0),
'B2u': (0,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.UCCSD(hf)
mycc.set(frozen = [0,1])
mycc.kernel()
```
Output for UCCSD:
```
converged SCF energy = -24.5320678037186
Traceback (most recent call last):
  File "sae.py", line 27, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 496, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 504, in ccsd
    if eris is None: eris = self.ao2mo(self.mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 528, in ao2mo
    return _ERIS(self, mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 2034, in __init__
    moidx = get_umoidx(cc)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 2279, in get_umoidx
    if len(frozen[0]) > 0:
TypeError: object of type 'int' has no len()
```
Output for CCSD:
```
converged SCF energy = -24.5320678037186
Traceback (most recent call last):
  File "sae.py", line 27, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd.py", line 561, in kernel
    return self.ccsd(t1, t2, eris)
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd.py", line 568, in ccsd
    eris = self.ao2mo(self.mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd.py", line 641, in ao2mo
    return _ERIS(self, mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd.py", line 809, in __init__
    self.mo_coeff = mo_coeff = _mo_without_core(cc, mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd.py", line 983, in _mo_without_core
    return mo[:,moidx]
TypeError: tuple indices must be integers, not tuple
```
Thank you.

**Comment by tberkel** [comment]
In UCCSD, frozen should be a length-two list of lists corresponding to the frozen orbitals for each spin.  Again, we could probably report the errors more insightfully.

**Comment by aannabe** [comment]
@tberkel Got it, thank you

**Comment by aannabe** [comment]
Hi, I still think there are issues with frozen orbitals in UCCSD. It doesn't occur in all states though. The one above works perfectly, but if I take another atomic state I encounter errors:
``` python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpvtz'}
mol.symmetry = 'D2h'
mol.spin = 3
mol.charge = 0
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (2,1),
'B3u': (1,0),
'B2u': (1,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.UCCSD(hf)
mycc.set(frozen = [[0],[0]])
mycc.kernel()
```
Output:
```
converged SCF energy = -24.451309880175
Warn: Overwrite cc.orbspin by _ERIS.
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 496, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 515, in ccsd
    verbose=self.verbose)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 58, in kernel
    t1, t2 = cc.vector_to_amplitudes(vec)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 1672, in vector_to_amplitudes
    t2ab = vector[-sizeab:].copy().reshape(nocca,noccb,nvira,nvirb)
ValueError: cannot reshape array of size 1053 into shape (3,0,26,29)
```
