### ISSUE TITLE
CCSD doesn't work for atom

### ISSUE THREAD

**Issue by gmwang18** [sunqm/pyscf#104]
Here is the code:

from pyscf import gto, scf, cc

mol = gto.M(
    atom = 'O 0 0 0',
    spin = 2,
    basis = 'ccpvdz')
mf = scf.RHF(mol).run()
mycc = cc.CCSD(mf).run()

here is the error information:
converged SCF energy = -74.7875130746235
Traceback (most recent call last):
  File "den_mat.py", line 8, in <module>
    mycc = cc.CCSD(mf).run()
  File "/home/gwang18/software/pyscf/pyscf/lib/misc.py", line 299, in run
    self.kernel(*args)
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 561, in kernel
    return self.ccsd(t1, t2, eris)
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 572, in ccsd
    verbose=self.verbose)
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 32, in kernel
    t1, t2 = mycc.init_amps(eris)[1:]
  File "/home/gwang18/software/pyscf/pyscf/cc/ccsd.py", line 544, in init_amps
    t1 = eris.fock[:nocc,nocc:] / eia
ValueError: operands could not be broadcast together with shapes (4,0,14) (4,10,2)

**Comment by gkc1000** [comment]
This is related to the recent bug report: the calculation has to run UCCSD,
not CCSD. This is fixed in the latest version I think.

**Comment by gmwang18** [comment]
Got it. Thanks.
