### ISSUE TITLE
CCSD(T) method fails on an atom

### ISSUE THREAD

**Issue by aannabe** [sunqm/pyscf#106]
I am having problems with CCSD(T) on an atom. Please take a look:
``` python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc,lib
from pyscf.cc import ccsd_t
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpvqz'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 0
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (2,2),
'B3u': (1,0),
'B2u': (0,0),
'B1g': (0,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.UCCSD(hf)
mycc.kernel()
ccsd_t.kernel(mycc, mycc.ao2mo())
```
Output:
```
converged SCF energy = -24.5329671386714
E(CCSD) = -24.62170859420476  E_corr = -0.08874145553337692
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    ccsd_t.kernel(mycc, mycc.ao2mo())
  File "/home/gani/codes/pyscf/pyscf/cc/ccsd_t.py", line 34, in kernel
    nocc, nvir = t1.shape
AttributeError: 'tuple' object has no attribute 'shape'
```

**Comment by sunqm** [comment]
UCCSD(T) is not available.  It probably will be implemented next month or September.

**Comment by aannabe** [comment]
OK, just so you know, CCSD method fails as well in this example(for ROHF and UHF), which is needed for CCSD(T).
