### ISSUE TITLE
PBC 09-Band ASE Example Error

### ISSUE THREAD

**Issue by jordangarside** [sunqm/pyscf#140]
I get this error when running the [band structure example](https://github.com/sunqm/pyscf/blob/73ff32c5e879b4892d4e3416b7aebf187054a0b6/examples/pbc/09-band_ase.py):
```
Traceback (most recent call last):
  File "09-band_ase.py", line 35, in <module>
    e_kn = mf.get_bands(band_kpts)[0]
  File "/home/jordan/Packages/pyscf/pyscf/pbc/scf/hf.py", line 152, in get_bands
    fock = fock + mf.get_veff(cell, dm, kpt=kpt, kpts_band=kpts_band)
  File "/home/jordan/Packages/pyscf/pyscf/pbc/dft/rks.py", line 67, in get_veff
    vj = ks.get_j(cell, dm, hermi, kpt, kpts_band)
  File "/home/jordan/Packages/pyscf/pyscf/pbc/scf/hf.py", line 367, in get_j
    return vj.reshape(dm.shape)
ValueError: cannot reshape array of size 1920 into shape (8,8)
```

**Comment by jordangarside** [comment]
Thanks Qiming!
