### ISSUE TITLE
OSError("no file with expected extension"), libcc not found?

### ISSUE THREAD

**Issue by fernandodelaiglesia** [sunqm/pyscf#141]
Hi,

I installed pyscf using pip in my Fedora25 desktop:

```
# export LDFLAGS='-L/usr/lib64/libblas.so -lblas'
# pip2 install pyscf
Collecting pyscf
  Using cached pyscf-1.4.0.9.tar.gz
Requirement already satisfied: numpy in /usr/lib64/python2.7/site-packages (from pyscf)
Requirement already satisfied: scipy in /usr/lib64/python2.7/site-packages (from pyscf)
Requirement already satisfied: h5py in /usr/lib64/python2.7/site-packages (from pyscf)
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from h5py->pyscf)
Installing collected packages: pyscf
  Running setup.py install for pyscf ... done
Successfully installed pyscf-1.4.0.9
```
And I'm trying to run some example with openfermion using pyscf, but it fails with

```
$ python2 diatomic.py 
Traceback (most recent call last):
  File "diatomic.py", line 18, in <module>
    from openfermionpyscf import run_pyscf
  File "/usr/lib/python2.7/site-packages/openfermionpyscf/__init__.py", line 20, in <module>
    from ._run_pyscf import run_pyscf
  File "/usr/lib/python2.7/site-packages/openfermionpyscf/_run_pyscf.py", line 20, in <module>
    from pyscf import ci, cc, fci, mp
  File "/usr/lib64/python2.7/site-packages/pyscf/ci/__init__.py", line 1, in <module>
    from pyscf.ci import cisd
  File "/usr/lib64/python2.7/site-packages/pyscf/ci/cisd.py", line 20, in <module>
    from pyscf.cc import ccsd
  File "/usr/lib64/python2.7/site-packages/pyscf/cc/__init__.py", line 49, in <module>
    from pyscf.cc import ccsd
  File "/usr/lib64/python2.7/site-packages/pyscf/cc/ccsd.py", line 17, in <module>
    from pyscf.cc import _ccsd
  File "/usr/lib64/python2.7/site-packages/pyscf/cc/_ccsd.py", line 8, in <module>
    libcc = lib.load_library('libcc')
  File "/usr/lib64/python2.7/site-packages/pyscf/lib/misc.py", line 43, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/usr/lib64/python2.7/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```
It seems that libcc.so is not present, but I'm unable to find any package for my Fedora25 that contains this library.

Any help will be welcome
Thaks in advance
Best

**Comment by sunqm** [comment]
I Forgot to add the cc module in setup.py.  It's fixed in 09c72e4
