### ISSUE TITLE
Coulomb energy has imaginary part

### ISSUE THREAD

**Issue by pulkin** [sunqm/pyscf#162]
A pbc hf calculation of a 2x2x2 copper supercell with a single k-point shifted away from bz symmetries using KRHF of dev branch. The problem may also be in RHF (did not try it out).

MWE:

```python
#!/usr/bin/python
from pyscf.pbc.scf import KRHF, RHF
from pyscf.pbc.gto import Cell

"""
Copper 2x2x2 supercell, structure from

https://materialsproject.org/materials/mp-30/

(may require login)
"""
c = Cell()
c.atom=[
    ('Cu', [ 0.        ,  0.        ,  0.        ]),
    ('Cu', [ 2.21458811,  0.        ,  1.27859304]),
    ('Cu', [ 0.73819604,  2.08793369,  1.27859304]),
    ('Cu', [ 2.95278415,  2.08793369,  2.55718608]),
    ('Cu', [ 0.        ,  0.        ,  2.55718608]),
    ('Cu', [ 2.21458811,  0.        ,  3.83577912]),
    ('Cu', [ 0.73819604,  2.08793369,  3.83577912]),
    ('Cu', [ 2.95278415,  2.08793369,  5.11437216]),
]
c.a = [
    [ 4.42917622,  0.        ,  2.55718608],
    [ 1.47639208,  4.17586738,  2.55718608],
    [ 0.        ,  0.        ,  5.11437216],
]
c.unit='Angstrom'
c.verbose=4
c.max_memory=128e3
c.basis='dzvp'
c.dimension = 3
c.build()

k=[[0.3, 0.1, 0.4]]

if False:
    KRHF = RHF
    k = k[0]

model_hf = KRHF(c, c.get_abs_kpts(k)).density_fit()
model_hf.kernel()
```

Output:

```
...
method = KRHF-KSCF-SCF
initial guess = minao
damping factor = 0
level shift factor = 0
DIIS = <class 'pyscf.scf.diis.CDIIS'>
DIIS start cycle = 1
DIIS space = 8
SCF tol = 1e-09
SCF gradient tol = None
max. SCF cycles = 50
direct_scf = False
chkfile to save SCF result = /tmp/tmpqCsXjl
max_memory 128000 MB (current use 91 MB)
...
N kpts = 1
...
init E= -13112.8287959055
HOMO = 0.368169760134  LUMO = 0.369513646937
Traceback (most recent call last):
  File "./mwe_cu_convergence.py", line 35, in <module>
    model_hf.kernel()
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/scf/hf.py", line 1367, in kernel
    return self.scf(dm0, **kwargs)
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/scf/hf.py", line 1361, in scf
    conv_check=self.conv_check, **kwargs)
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/scf/hf.py", line 142, in kernel
    e_tot = mf.energy_tot(dm, h1e, vhf)
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/scf/hf.py", line 236, in energy_tot
    e_tot = mf.energy_elec(dm, h1e, vhf)[0] + mf.energy_nuc()
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/pbc/scf/khf.py", line 212, in energy_elec
    "something is wrong!", e_coul.imag)
RuntimeError: ('Coulomb energy has imaginary part, something is wrong!', 0.0071160761265044239)
```

**Comment by sunqm** [comment]
This error is due to a greedy energy cutoff when computing nuclear attraction.  Using the fix in dev branch, you should get the total SCF energy -13109.2015890721
