### ISSUE TITLE
Problem in mytd.analyze()?

### ISSUE THREAD

**Issue by lucamontana** [sunqm/pyscf#196]
Hi, any idea how to get rid of the error of mytd.analyze()?

----------------------------------------------------------------------
python  00-simple_tddft.py 

converged SCF energy = -100.351093597227
Excited State energies (eV)
[  7.60451924   7.60451924  13.61707271]

** Singlet excitation energies and oscillator strengths **
Traceback (most recent call last):
  File "00-simple_tddft.py", line 27, in <module>
    mytd.analyze()
  File "/home/luca/pyscf/pyscf/tdscf/rhf.py", line 368, in analyze
    f_oscillator = tdobj.oscillator_strength()
  File "/home/luca/pyscf/pyscf/tdscf/rhf.py", line 518, in oscillator_strength
    trans_dip = transition_dipole(tdobj, xy)
  File "/home/luca/pyscf/pyscf/tdscf/rhf.py", line 420, in transition_dipole
    return tdobj._contract_multipole(ints, hermi=True, xy=xy)
  File "/home/luca/pyscf/pyscf/tdscf/rhf.py", line 505, in _contract_multipole
    ints = numpy.einsum('...pq,pi,qj->...ij', ints, orbo.conj(), orbv)
ValueError: operand 1 did not have enough dimensions to match the broadcasting, and couldn't be extended because einstein sum subscripts were specified at both the start and end

**Comment by sunqm** [comment]
Which version are you using? I cannot reproduce this error with the pypi release, or the HEAD on the master branch or dev branch.

**Comment by lucamontana** [comment]
I am using the last version from master branch. strange.

**Comment by lucamontana** [comment]
I recompiled the latest version, now the mytd.analyz() error disappears, however when I run:
python 01-nto_analysis.py   I get:

converged SCF energy = -100.351093597227
Excited State energies (eV)
[  7.60451924   7.60451924  13.61707271]
Traceback (most recent call last):
File "01-nto_analysis.py", line 26, in <module>
weights_1, nto_1 = mytd.get_nto(state=1, verbose=4)
File "/home/luca/pyscf/pyscf/tdscf/rhf.py", line 287, in get_nto
weights_o[idx], nto_o[idx[:,None],idx] = numpy.linalg.eigh(dm_oo)
ValueError: array is not broadcastable to correct shape
