### ISSUE TITLE
block error

### ISSUE THREAD

**Issue by jamcas** [sunqm/pyscf#231]
When i do DMRGSCF.i meet the following error:
```
******** Block flags ********
executable             = /home/chenh/ly/sourcefoldersto/block-1.5.3_mpi/block.spin_adapted
BLOCKEXE_COMPRESS_NEVPT= /home/chenh/ly/sourcefoldersto/block-1.5.3/block.spin_adapted
Block version          = 1.5.3
mpiprefix              = mpirun -n 16
scratchDirectory       = /home/chenh/ly/documents/7260
integralFile           = 7260/FCIDUMP
configFile             = 7260/dmrg.conf
outputFile             = 7260/dmrg.out
maxIter                = 38
scheduleSweeps         = [0, 4, 8, 12, 14, 16, 18, 20, 22]
scheduleMaxMs          = [200, 400, 800, 1000, 1000, 1000, 1000, 1000, 1000]
scheduleTols           = [1e-05, 1e-05, 1e-05, 1e-05, 1.0000000000000002e-06, 1.0000000000000002e-07, 1.0000000000000002e-08, 1.0000000000000003e-09, 1e-09]
scheduleNoises         = [1e-05, 1e-05, 1e-05, 5e-05, 5e-05, 5e-05, 5e-05, 5e-05, 0.0]
twodot_to_onedot       = 26
tol                    = 1e-09
maxM                   = 1000
dmrg switch tol        = 0.001
wfnsym                 = 1
fullrestart            = False
num_thrds              = 1
memory                 = None

Start 1-step CASSCF
Start CASCI
    CPU time for integral transformation to CAS space      0.00 sec, wall time      0.00 sec
core energy = -70.5529830711626
    CPU time for effective h1e in CAS space      0.00 sec, wall time      0.00 sec

ERROR: mpirun -n 16 /home/chenh/ly/sourcefoldersto/block-1.5.3_mpi/block.spin_adapted dmrg.conf > dmrg.out 2>&1

/home/chenh/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
ERROR: mpirun -n 16 /home/chenh/ly/sourcefoldersto/block-1.5.3_mpi/block.spin_adapted dmrg.conf > dmrg.out 2>&1
Traceback (most recent call last):
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 904, in executeBLOCK
    check_call(cmd, cwd=DMRGCI.runtimeDir, shell=True)
  File "/home/chenh/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mpirun -n 16 /home/chenh/ly/sourcefoldersto/block-1.5.3_mpi/block.spin_adapted dmrg.conf > dmrg.out 2>&1' returned non-zero exit status 132.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 8, in <module>
    mc.kernel()
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 766, in kernel
    ci0=ci0, callback=callback, verbose=self.verbose)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 345, in kernel
    e_tot, e_cas, fcivec = casscf.casci(mo, ci0, eris, log, locals())
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/mc1step.py", line 786, in casci
    e_tot, e_cas, fcivec = casci.kernel(fcasci, mo_coeff, ci0, log)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/mcscf/casci.py", line 504, in kernel
    ecore=energy_core)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 706, in kernel
    executeBLOCK(self)
  File "/home/chenh/anaconda3/lib/python3.6/site-packages/pyscf/dmrgscf/dmrgci.py", line 908, in executeBLOCK
    DMRGCI.stdout.write(check_output(['tail', '-100', outFile]))
TypeError: write() argument must be str, not bytes

```
The input file is:
```
import os
from pyscf import gto, scf, mcscf, dmrgscf, mrpt
dmrgscf.settings.MPIPREFIX = 'mpirun -n 16'

os.system('date')
mol = gto.M(atom='C 0 0 0; C 0 0 1', basis='631g', verbose=5)
mf = scf.RHF(mol).run()
mc = dmrgscf.DMRGSCF(mf, 4, 4)
mc.kernel()
mrpt.NEVPT(mc).compress_approx().kernel()
os.system('date')
```

**Comment by sunqm** [comment]
You might be using an old version. This bug was fixed in any releases later than 1.5.0. The version can be found with the cmd
$ python -c 'import pyscf; print pyscf.__version__'

**Comment by jamcas** [comment]
I use the `$ python -c 'import pyscf; print pyscf.version'`,but it shows me:
`AttributeError: module 'pyscf' has no attribute 'version'`

I find in the out file that my pyscf version is the latest:
```
System: uname_result(system='Linux', node='Pauling', release='2.6.32-279.el6.x86_64', version='#1 SMP Wed Jun 13 18:24:36 EDT 2012', machine='x86_64', processor='x86_64')  Threads 16
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0]
numpy 1.14.3  scipy 1.1.0
Date: Sat Sep 29 15:24:39 2018
PySCF version 1.5.3
PySCF path  /home/chenh/anaconda3/lib/python3.6/site-packages/pyscf

```

**Comment by sunqm** [comment]
The bug in the Python side interface is fixed.

In the directory /home/chenh/ly/documents/7260, run
```
mpirun -n 16 /home/chenh/ly/sourcefoldersto/block-1.5.3_mpi/block.spin_adapted dmrg.conf
```
What output/error do you get?

**Comment by jamcas** [comment]
$ mpirun -n 16 /home/chenh/ly/sourcefolders/block-1.5.3_mpi/block.spin_adapted dmrg.conf 
```
[node6:109837] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109835] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109839] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109842] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109840] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109841] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109836] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109844] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109846] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109849] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109845] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109843] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109838] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109848] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109847] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109850] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file ess_env_module.c at line 367
[node6:109840] [[INVALID],INVALID]-[[58147,0],0] mca_oob_tcp_peer_try_connect: connect to 255.255.255.255:57529 failed: Network is unreachable (101)
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58147,1],5]
  Exit code:    1
--------------------------------------------------------------------------

```

**Comment by sunqm** [comment]
It looks like a problem of OpenMPI communication. You may need to specify a communication device for OpenMPI OOB layer. It might be something like
export OMPI_MCA_btl_tcp_if_include=eth0,ib0
export OMPI_MCA_oob_tcp_if_include=eth0,ib0

You may need to google it.

**Comment by jamcas** [comment]
Thanks! I think there is something wrong with my openmpi, After i re-install it ,the block works now
