### ISSUE TITLE
EOM-K-CCSD bug

### ISSUE THREAD

**Issue by pulkin** [sunqm/pyscf#232]
This issue was around for quite a while: test `pyscf.pbc.cc.test.test_kpoint_rhf.KnownValues.test_cu_metallic_high_cost` actually fails on `dev` branch on my computer. By fact, it is `_test_cu_metallic_frozen_vir` which fails (it is called only by `test_cu_metallic_high_cost`). From my experience the problem is rather general: calling `cc.ipccsd` and `cc.eaccsd` with `nroots>1` for all models I study will raise it. On the other hand, test `test_h4_fcc_k2` passes. Stack trace:

```
======================================================================
ERROR: test_cu_metallic_high_cost (test_kpoint_rhf.KnownValues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pulkin/Projects/pyscf-mine/pyscf/pyscf/pbc/cc/test/test_kpoint_rhf.py", line 388, in test_cu_metallic_high_cost
    self._test_cu_metallic_frozen_vir(kmf, cell)
  File "/home/pulkin/Projects/pyscf-mine/pyscf/pyscf/pbc/cc/test/test_kpoint_rhf.py", line 327, in _test_cu_metallic_frozen_vir
    ew, ev = mycc.ipccsd(nroots=3, koopmans=True, kptlist=[1])
  File "/home/pulkin/.local/lib/python2.7/site-packages/pyscf/pbc/cc/kccsd_rhf.py", line 721, in ipccsd
    evals[k] = evals_k
ValueError: could not broadcast input array from shape (2) into shape (3)
```

**Comment by pulkin** [comment]
Changing to `koopmans=False` in https://github.com/sunqm/pyscf/blob/c29348d5a88fd06453d0eae5ad0d04f44d6d3010/pyscf/pbc/cc/test/test_kpoint_rhf.py#L327 will fix this exception.
