### ISSUE TITLE
NameError for geometric_solver

### ISSUE THREAD

**Issue by xptree** [sunqm/pyscf#4]
```
###job_id=1004###
smi: CC1C2CC34CC(CCC13)C2C4N
xyz: 
C          1.16810        1.64984        0.05542
C          0.16251        1.81910        1.19589
C         -1.41950        1.49758        0.78707
C         -1.54673        2.82306        0.36084
C         -1.23866        3.13021        2.26319
C         -2.03478        4.26805        2.88680
C         -2.86592        4.02119        1.70259
C         -1.78633        5.06937        0.79941
C         -0.09655        4.69359        1.09360
C          0.15701        3.28364        1.88359
C         -2.68549        2.10172        1.72673
C         -1.95339        1.97661        3.00408
N         -1.38469        0.71158        3.40335
H          0.92091        2.21594       -0.84543
H          1.22399        0.59395       -0.23223
H          2.16585        1.96162        0.38014
H          0.48577        1.09424        1.94999
H         -1.63677        0.73082        0.04561
H         -2.52669        2.98681       -0.14061
H         -0.79862        3.15204       -0.36832
H         -1.52550        5.22511        3.02873
H         -2.56238        4.09809        3.82959
H         -3.90622        4.34978        1.73124
H         -2.00577        5.05354       -0.27579
H         -1.94773        6.10727        1.12526
H          0.46999        4.75603        0.15781
H          0.27535        5.50490        1.73449
H          0.88338        3.37690        2.69317
H         -3.64916        1.59730        1.61140
H         -2.61178        2.24524        3.83416
H         -1.23117        0.06852        2.63319
H         -0.49377        0.86162        3.87311
```

```python
Traceback (most recent call last):
  File "/root/anaconda3/bin/dispynode.py", line 208, in _dispy_job_func
    __dispy_job_name, globals(), localvars)
  File "<string>", line 1, in <module>
  File "<string>", line 18, in compute
  File "./pyscf_geomopt.py", line 99, in hfsto3g
    mol_sto3g = optimize(mf, grad_cb)
  File "./pyscf_geomopt.py", line 64, in optimize
    opt.kernel()
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 171, in kernel
    maxsteps=self.max_cycle, **self.params)
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 119, in kernel
    constraints=constraints, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1708, in run_optimizer
    progress = Optimize(coords, M, IC, engine, dirname, params, xyzout)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1300, in Optimize
    return optimizer.optimizeGeometry()
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1267, in optimizeGeometry
    self.calcEnergyForce()
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 979, in calcEnergyForce
    self.E, self.gradx = self.engine.calc(self.X, self.dirname)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/engine.py", line 164, in calc
    energy, gradient = self.calc_new(coords, dirname)
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 77, in calc_new
    raise RuntimeError('Nuclear gradients of %s not converged' % scanner.base)
NameError: name 'scanner' is not defined
```

**Comment by sunqm** [comment]
Fixed in 7cea335a023c54bf1a1d2c5a732ef3a0519dfe7e
