### ISSUE TITLE
Doesn't work with Python 3.4

### ISSUE THREAD

**Issue by berquist** [sunqm/pyscf#47]
```
/home/eric/development/pyscf/examples/ao2mo on master! (env: 3.4 3.4.5)
[eric@copper]$ OMP_NUM_THREADS=1 python 00-mo_integrals.py
converged SCF energy = -99.9873974403482
Traceback (most recent call last):
  File "00-mo_integrals.py", line 23, in <module>
    eri_4fold = ao2mo.kernel(mol, orb)
  File "/home/eric/development/pyscf/ao2mo/__init__.py", line 301, in kernel
    return full(eri_or_mol, mo_coeffs, *args, **kwargs)
  File "/home/eric/development/pyscf/ao2mo/__init__.py", line 139, in full
    return fn(eri_or_mol, mo_coeff, *args, **kwargs)
  File "/home/eric/development/pyscf/ao2mo/outcore.py", line 589, in full_iofree
    verbose=verbose, compact=compact)
  File "/home/eric/development/pyscf/ao2mo/outcore.py", line 263, in general
    log, compact)
  File "/home/eric/development/pyscf/ao2mo/outcore.py", line 477, in half_e1
    write_handler = async_write(istep, iobuf, write_handler)
  File "/home/eric/development/pyscf/ao2mo/outcore.py", line 450, in async_write
    thread_io = lib.background_thread(save, istep, iobuf)
  File "/home/eric/development/pyscf/lib/misc.py", line 415, in background_thread
    thread = ThreadWithReturnValue(target=func, args=args, kwargs=kwargs)
  File "/home/eric/development/pyscf/lib/misc.py", line 407, in __init__
    Thread.__init__(self, group, qwrap, name, args, kwargs, verbose)
TypeError: __init__() takes from 1 to 6 positional arguments but 7 were given
```

**Comment by gkc1000** [comment]
Hi Eric, PySCF is a Python 2 module, not a Python 3 module. You should download a Python 2.7 environment, e.g. through the Anaconda distribution.
