### ISSUE TITLE
numpy LinAlgError for geometric_solver

### ISSUE THREAD

**Issue by xptree** [sunqm/pyscf#5]
```
###job_id=1387###
smi: CC1=C2CC(=C)C(CO)=CC2=CC1
xyz: 
C          1.04315        0.06343        0.06415
C          0.53648        1.15267        0.99540
C          0.86513        1.12633        2.31525
C          2.19617        0.69234        2.99127
C          1.97937        0.13966        4.40504
C          2.88701       -0.55983        5.08448
C          0.59903        0.29433        4.90490
C          0.43961        1.04818        6.20467
O          1.20477        2.26239        6.18177
C         -0.40201       -0.04276        4.04716
C          0.01086       -0.03020        2.64964
C         -0.00456       -0.82064        1.53850
C          1.04315        0.06343        0.06415
H          1.41905        0.29764       -1.42012
H          1.85959       -1.16941        0.52029
H          2.45296        0.69578        0.17132
H          2.70453       -0.08176        2.39823
H          2.86475        1.55731        3.03994
H          2.66274       -0.99851        6.05717
H          3.87313       -0.76725        4.67422
H         -0.59717        1.34843        6.37698
H          0.78177        0.45892        7.05864
H          2.10498        2.03768        5.88820
H         -1.44557        0.15189        4.27799
H         -0.47598       -1.77803        1.36270
H          0.45296       -1.15227       -0.69070
H         -0.10876        0.65140       -0.79591
```

```python
Traceback (most recent call last):
  File "/root/anaconda3/bin/dispynode.py", line 208, in _dispy_job_func
    __dispy_job_name, globals(), localvars)
  File "<string>", line 1, in <module>
  File "<string>", line 18, in compute
  File "./pyscf_geomopt.py", line 99, in hfsto3g
    mol_sto3g = optimize(mf, grad_cb)
  File "./pyscf_geomopt.py", line 64, in optimize
    opt.kernel()
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 171, in kernel
    maxsteps=self.max_cycle, **self.params)
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 119, in kernel
    constraints=constraints, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1708, in run_optimizer
    progress = Optimize(coords, M, IC, engine, dirname, params, xyzout)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1300, in Optimize
    return optimizer.optimizeGeometry()
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 1262, in optimizeGeometry
    self.calcEnergyForce()
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/optimize.py", line 979, in calcEnergyForce
    self.E, self.gradx = self.engine.calc(self.X, self.dirname)
  File "/root/anaconda3/lib/python3.7/site-packages/geometric-0.9.4+15.g75989d0-py3.7.egg/geometric/engine.py", line 164, in calc
    energy, gradient = self.calc_new(coords, dirname)
  File "/root/pyscf/pyscf/geomopt/geometric_solver.py", line 71, in calc_new
    energy, gradients = g_scanner(mol)
  File "/root/pyscf/pyscf/grad/rhf.py", line 193, in __call__
    e_tot = mf_scanner(mol)
  File "/root/pyscf/pyscf/scf/hf.py", line 1168, in __call__
    e_tot = self.kernel(dm0=dm0, **kwargs)
  File "/root/pyscf/pyscf/lib/misc.py", line 584, in aliased_fn
    return getattr(self, fname)(*args, **kwargs)
  File "/root/pyscf/pyscf/scf/hf.py", line 1501, in scf
    conv_check=self.conv_check, **kwargs)
  File "/root/pyscf/pyscf/scf/hf.py", line 121, in kernel
    dm = mf.get_init_guess(mol, mf.init_guess)
  File "/root/pyscf/pyscf/scf/hf.py", line 1445, in get_init_guess
    dm = self.init_guess_by_minao(mol)
  File "/root/pyscf/pyscf/scf/hf.py", line 1396, in init_guess_by_minao
    return init_guess_by_minao(mol)
  File "/root/pyscf/pyscf/scf/hf.py", line 433, in init_guess_by_minao
    c = addons.project_mo_nr2nr(pmol, numpy.eye(pmol.nao_nr()), mol)
  File "/root/pyscf/pyscf/scf/addons.py", line 303, in project_mo_nr2nr
    return lib.cho_solve(s22, numpy.dot(s21, mo1))
  File "/root/pyscf/pyscf/lib/linalg_helper.py", line 1394, in cho_solve
    return scipy.linalg.solve(a, b, sym_pos=True)
  File "/root/anaconda3/lib/python3.7/site-packages/scipy/linalg/basic.py", line 250, in solve
    _solve_check(n, info)
  File "/root/anaconda3/lib/python3.7/site-packages/scipy/linalg/basic.py", line 31, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.linalg.LinAlgError: Matrix is singular
```

**Comment by gkc1000** [comment]
This error is from your input geometry, which is invalid. Notice that the
1st carbon and last carbon have exactly the same coordinate (i.e. they are
on top of each other).

**Comment by xptree** [comment]
Thanks for you quick reply @gkc1000. Let me explain a little about how I met this error. Basicly I have some SMILE strings and I use openbabel to provide an initial geometry. Then I call PySCF for fine-grained geometry. It seems that openbabel sometimes give me bad initialization. Do you have any suggestions to avoid this problem?

**Comment by gkc1000** [comment]
I think the best thing is to write an external script to do a little bit of
cleanup of the openbabel geometry. How to handle overlapping atoms involves
choice, and so it shouldn't be dictated by pyscf. What you could do in
practice is randomly move atoms that you detect to be overlapping.

BTW, please post issues to the official repository pyscf/pyscf. This issue
will now be marked as closed.
