### ISSUE TITLE
RuntimeError when running GDB17

### ISSUE THREAD

**Issue by xptree** [sunqm/pyscf#7]
```python
Traceback (most recent call last):
  File "/root/anaconda3/bin/dispynode.py", line 208, in _dispy_job_func
    __dispy_job_name, globals(), localvars)
  File "<string>", line 1, in <module>
  File "<string>", line 13, in compute
  File "/root/pyscf/pyscf/gto/mole.py", line 2119, in build
    self.nelec
  File "/root/pyscf/pyscf/gto/mole.py", line 1907, in nelec
    (ne, self.spin))
RuntimeError: Electron number 133 and spin 0 are not consistent
Note mol.spin = 2S = Nalpha - Nbeta, not 2S+1
```

**Comment by tberkel** [comment]
This is not a PySCF error, and the RuntimeError tells you what the problem
is.  The molecule you have entered has an odd number of electrons (133) and
so it is open shell and needs to have the spin specified.  Or possibly, the
molecule is specified incorrectly or meant to be charged.
