### ISSUE TITLE
Direct CCSD failed when frozen core is used

### ISSUE THREAD

**Issue by pchong90** [sunqm/pyscf#72]
I am using pyscf release 1.3.

If `frozen=0` then the program will finish without error. However, the program failed if `frozen core` is used as well as `direct` is used. 

I posted the input here, hope I didn't make any mistakes in input.

Input:
```
from pyscf import gto, scf, cc
mol = gto.M(atom = 'H 0 0 0; F 0 0 1.1', basis = 'ccpvdz')
mol.verbose = 5
mf = scf.RHF(mol).run()
mycc = cc.CCSD(mf)
mycc.frozen = 1
mycc.direct = True
mycc.run()
```
Output:
```
******** <class 'pyscf.cc.ccsd.CCSD'> flags ********
CCSD nocc = 4, nvir = 14
frozen orbitals 1
max_cycle = 50
direct = 1
conv_tol = 1e-07
conv_tol_normt = 1e-05
diis_space = 6
diis_start_cycle = 0
diis_start_energy_diff = 1e+09
    CPU time for CCSD integral transformation      0.16 sec, wall time      0.01 sec
Init t2, MP2 energy = -0.209289266060397
    CPU time for init mp2      0.00 sec, wall time      0.00 sec
Traceback (most recent call last):
  File "ccsd.py", line 9, in <module>
    mycc.run()
  File "/pyscf/pyscf/lib/misc.py", line 299, in run
    self.kernel(*args)
  File "/pyscf/pyscf/cc/ccsd.py", line 560, in kernel
    return self.ccsd(t1, t2, eris)
  File "/pyscf/pyscf/cc/ccsd.py", line 571, in ccsd
    verbose=self.verbose)
  File "/pyscf/pyscf/cc/ccsd.py", line 51, in kernel
    t1new, t2new = mycc.update_amps(t1, t2, eris)
  File "/pyscf/pyscf/cc/ccsd.py", line 79, in update_amps
    mycc.add_wvvVV_(t1, t2, eris, t2new_tril)
  File "/pyscf/pyscf/cc/ccsd.py", line 732, in add_wvvVV_
    t2new_tril += tmp.reshape(-1,nvir,nvir)
ValueError: total size of new array must be unchanged
```

**Comment by sunqm** [comment]
AO driven frozen-core CCSD was not implemented in 1.3 release.

**Comment by pchong90** [comment]
Thanks for reply. I just encountered this error when I was trying to play around with PySCF. Is it available on master branch or it is not implemented?

**Comment by sunqm** [comment]
Seems not difficult to have the frozen core code working with a small fix.  The test code should work on both master branch and dev branch.
