### ISSUE TITLE
Testcase fails: no such file - libnp_helper

### ISSUE THREAD

**Issue by yurivict** [sunqm/pyscf#83]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pyscf import gto, scf
  File "/usr/local/lib/python2.7/site-packages/pyscf/__init__.py", line 118, in <module>
    from pyscf import gto
  File "/usr/local/lib/python2.7/site-packages/pyscf/gto/__init__.py", line 7, in <module>
    from pyscf.gto import mole
  File "/usr/local/lib/python2.7/site-packages/pyscf/gto/mole.py", line 17, in <module>
    from pyscf import lib
  File "/usr/local/lib/python2.7/site-packages/pyscf/lib/__init__.py", line 11, in <module>
    from pyscf.lib import numpy_helper
  File "/usr/local/lib/python2.7/site-packages/pyscf/lib/numpy_helper.py", line 17, in <module>
    _np_helper = misc.load_library('libnp_helper')
  File "/usr/local/lib/python2.7/site-packages/pyscf/lib/misc.py", line 41, in load_library
    return numpy.ctypeslib.load_library(libname, _loaderpath)
  File "/usr/local/lib/python2.7/site-packages/numpy/ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

On FreeBSD 11

**Comment by sunqm** [comment]
Do you install pyscf using the setup.py in the main directory?  The setup.py in the current version does not compile the C code automatically.  You need to first compile the C library in pyscf/lib directory as shown in the document   http://sunqm.github.io/pyscf/tutorial.html#quick-setup, then run "python setup.py install".

**Comment by yurivict** [comment]
Thanks!
