### ISSUE TITLE
UCCSD value error

### ISSUE THREAD

**Issue by aannabe** [sunqm/pyscf#97]
Hi, I am looking at B(++) 1s2 3d1 state. I want to use UCCSD but I get a ValueError. Here is my piece of code and the output:

```python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpv5z'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 2
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (1,1),
'B3u': (0,0),
'B2u': (0,0),
'B1g': (1,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.UCCSD(hf)
mycc.kernel()
```
Output:
```
converged SCF energy = -22.4790012900203
Traceback (most recent call last):
  File "Bae.py", line 26, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 496, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 515, in ccsd
    verbose=self.verbose)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 58, in kernel
    t1, t2 = cc.vector_to_amplitudes(vec)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 1671, in vector_to_amplitudes
    t1b, t2bb = self.vector_to_amplitudes_ee(vector[sizea:sizea+sizeb], noccb, nvirb)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 1636, in vector_to_amplitudes_ee
    return self.vector_to_amplitudes_s4(vector, nocc, nvir)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 1421, in vector_to_amplitudes_s4
    t2tril = vector[nov:size].reshape(nocc*(nocc-1)//2, -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

**Comment by sunqm** [comment]
Fixed in latest commit.
