### ISSUE TITLE
RCCSD/UCCSD with ECP

### ISSUE THREAD

**Issue by aannabe** [sunqm/pyscf#99]
Hi again,
I have a B(++) 3d1 state with ECP. This state seems to be not working with both RCCSD and UCCSD. Here are inputs and outputs:

```python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpv5z'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 2
mol.ecp={'B':'bfd'}
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (0,0),
'B3u': (0,0),
'B2u': (0,0),
'B1g': (1,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
mycc = cc.UCCSD(hf)
mycc.kernel()
```

Output:

```
Traceback (most recent call last):
  File "Bpp.py", line 28, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 496, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 504, in ccsd
    if eris is None: eris = self.ao2mo(self.mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 528, in ao2mo
    return _ERIS(self, mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/uccsd.py", line 2039, in __init__
    self.mo_coeff = mo_coeff = [mo_coeff[0][:,moidx[0]],
IndexError: too many indices for array
```

RCCSD gives:

```
Traceback (most recent call last):
  File "Bpp.py", line 28, in <module>
    mycc.kernel()
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 191, in kernel
    return self.ccsd(t1, t2, eris, mbpt2)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 199, in ccsd
    if eris is None: eris = self.ao2mo(self.mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 223, in ao2mo
    return _ERIS(self, mo_coeff)
  File "/home/gani/codes/pyscf/pyscf/cc/rccsd.py", line 1494, in __init__
    self.ovvv = lib.pack_tril(ovvv).reshape(nocc,nvir,-1)
ValueError: cannot reshape array of size 0 into shape (0,91,newaxis)
```
Thank you

**Comment by aannabe** [comment]
Another observation. If I call hf.analayze() without UCCSD (scf only), I can see that the symmetry is incorrect. Here is what I mean:

```python
#! /usr/bin/env python
import sys,os
from pyscf import scf,gto,cc
mol = gto.Mole()
mol.atom = ''' B 0.0 0.0 0.0 '''
mol.basis = {'B': 'ccpv5z'}
mol.symmetry = 'D2h'
mol.spin = 1
mol.charge = 2
mol.ecp={'B':'bfd'}
mol.build()
hf = scf.UHF(mol)
hf.irrep_nelec = {
'Ag' : (0,0),
'B3u': (0,0),
'B2u': (0,0),
'B1g': (1,0),
'B1u': (0,0),
'B2g': (0,0),
'B3g': (0,0),
'Au' : (0,0)
}
hf.kernel()
hf.analyze()
```

A few lines of the output [file](https://github.com/sunqm/pyscf/files/1107029/Bpp.txt)

```
total symmetry = Ag
occupancy for each irrep:     Ag  B1g  B2g  B3g   Au  B1u  B2u  B3u
double occ                     0    0    0    0    0    0    0    0
single occ                     1    0    0    0    0    0    0    0
**** MO energy ****
MO #1   (Ag #1 ), energy= -1.3894068569132   occ= 1
MO #2   (B2u #1 ), energy= -1.15830648198984  occ= 0
MO #3   (B3u #1 ), energy= -1.15830648198984  occ= 0
```

The symmetry is Ag instead of requested B1g. I am not sure if this is a bug or user input mistake.
